name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  run-cypress:
    name: Run Cypress Tests
    runs-on: ubuntu-latest
    # 使用官方 Cypress 浏览器镜像，确保环境一致:contentReference[oaicite:6]{index=6}
    container: cypress/browsers:node-22.14.0-chrome-133.0.6943.126-1-ff-135.0.1-edge-133.0.3065.82-1
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx cypress run

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/
